const mongoose=require('mongoose');

const profileSchema=new mongoose.Schema({
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'user'
    },
    company:String,
    website:String,
    location:String,
    status:{
        type:String,
        required:true
    },
    skills:{
        type:[String],
        required:true
    },
    bio:String,
    githubUserName:String,
    experience:[
        {
            title:{
                type:String,
                required:true,
            },
            company:{
                type:String,
                required:true
            },
            location:String,
            from:{
                type:Date,
                required:true,
            },
            to:Date,
            current:{
                type:Boolean,
                requires:true
            },
            description:String
        }
    ],
    education:[
        {
            school:{
                type:String,
                required:true
            },
            degree:{
                type:String,
                required:true
            },
            fieldOfStudy:String,
            from:{
                type:Date,
                required:true
            },
            to:Date,
            current:{
                type:Boolean,
                required:true
            },
            description:String
        }
    ],
    socail:{
        youtube:String,
        twitter:String,
        facebook:String,
        Instagram:String,
        LinkedIn:String
    },
    created_at:{
        type:Date,
        default:Date.now
    }
});

const Profile=mongoose.model('Profile',profileSchema);

modules.exports=Profile;